---
- hosts: localhost
  become: yes
  tasks:
  - name: create ec2 instances
    ec2:
     key_name: tower
     group: default
     instance_type: t2.micro
     image: ami-09f8a37134737968b
     region: us-east-1
     wait: yes
     count: 1
     instance_tags:
       Name: Dynamic
     vpc_subnet_id: subnet-a5abe48b
     assign_public_ip: yes
