---
# install java
# sudo apt-get install default-jdk -y
- name: install java
  apt:
    name: default-jdk
    state: present

# wget http://download.jboss.org/wildfly/14.0.1.Final/wildfly-14.0.1.Final.tar.gz
- name: Download jboss file tar.gz
  get_url:
    url: http://download.jboss.org/wildfly/14.0.1.Final/wildfly-14.0.1.Final.tar.gz
    dest: /opt
  ##  dest: /opt/wildfly-14.0.1.Final.tar.gz

# cd /opt
# tar -xvzf wildfly-14.0.1.Final.tar.gz
- name: Extract wildfly-14.0.1.Final.tar.gz into /opt
  unarchive:
    src: /opt/wildfly-14.0.1.Final.tar.gz
    dest: /opt/wildfly-14.0.1.Final

# sudo mv wildfly-14.0.1.Final wildfly
- name: Create a directory 
  file:
    path: /opt/wildfly
    state: directory

# move files from wildfly-14.0.1.Final to wildfly
- name: move fiels
  copy:
    src: /opt/wildfly-14.0.1.Final/*
    dest: /opt/wildfly

# sudo nano /opt/wildfly/standalone/configuration/standalone.xml
- name: tomcat user context
  template:
    src: templates/standalone.j2
    dest: /opt/wildfly/standalone/configuration/standalone.xml

# sudo /opt/wildfly/bin/add-user.sh
- name: Generic question with multiple different responses
  expect:
    command: /opt/wildfly/bin/add-user.sh
    responses:
      Question:
        - (a): a
        - Username : gowtham
        - Password : 1234
        - Are you sure you want to use the password entered yes/no? : yes

# sudo sh /opt/wildfly/bin/standalone.sh
- name: The below command will start the wildfly instance.
  command: sudo sh /opt/wildfly/bin/standalone.sh