---

- name: install java
  apt:
   name: default-jdk
   state: present

- name: download jboss(wildfly-14.0.1.Final.tar.gz)
  get_url:
      url: http://download.jboss.org/wildfly/14.0.1.Final/wildfly-14.0.1.Final.tar.gz
      dest: /opt/

- name: extract wildfly-14.0.1.Final.tar.gz
  unarchive:
      src: /opt/wildfly-14.0.1.Final.tar.gz
      dest: /opt/
      remote_src: yes

- name: rename file wildfly-14.0.1.Final.tar.gz to wildfly
  command: sudo mv wildfly-14.0.1.Final wildfly

- name: tomcat user context
  template:
    src: templates/standalone.j2
    dest: /opt/wildfly/standalone/configuration/standalone.xml

- name: Generic question with multiple different responses
  expect:
    command: /opt/wildfly/bin/add-user.sh
    responses:
      Question:
        - (a): a
        - Username : gowtham
        - Password : Gow@123
        - Are you sure you want to use the password entered yes/no? : yes

- name: execute shell command
  command: 
   shell: sudo sh /opt/wildfly/bin/standalone.sh
